import { writeFile } from 'fs/promises';
import { extname } from 'path';
import type { ScanSummary, CleanSummary } from '../types.js';
import { formatSize } from './size.js';

interface ScanReportData {
  type: 'scan';
  timestamp: string;
  summary: ScanSummary;
}

interface CleanReportData {
  type: 'clean';
  timestamp: string;
  dryRun: boolean;
  duration: number;
  summary: CleanSummary;
}

type ReportData = ScanReportData | CleanReportData;

export async function generateReport(
  outputPath: string,
  data: ReportData
): Promise<void> {
  const ext = extname(outputPath).toLowerCase();

  let content: string;
  if (ext === '.html') {
    content = generateHtmlReport(data);
  } else if (ext === '.md' || ext === '.markdown') {
    content = generateMarkdownReport(data);
  } else {
    // Default to markdown for unknown extensions
    content = generateMarkdownReport(data);
  }

  await writeFile(outputPath, content, 'utf-8');
}

function generateMarkdownReport(data: ReportData): string {
  const lines: string[] = [];
  const date = new Date(data.timestamp).toLocaleString();

  if (data.type === 'scan') {
    lines.push('# Windows Cleaner CLI - Scan Report');
    lines.push('');
    lines.push(`**Generated:** ${date}`);
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    lines.push(`- **Total Size:** ${formatSize(data.summary.totalSize)}`);
    lines.push(`- **Total Items:** ${data.summary.totalItems.toLocaleString()}`);
    lines.push(`- **Categories Scanned:** ${data.summary.results.length}`);
    lines.push('');
    lines.push('## Categories');
    lines.push('');
    lines.push('| Category | Safety | Size | Items |');
    lines.push('|----------|--------|------|-------|');

    for (const result of data.summary.results) {
      if (result.items.length > 0) {
        const safety = result.category.safetyLevel === 'safe' ? '🟢 Safe' :
                       result.category.safetyLevel === 'moderate' ? '🟡 Moderate' : '🔴 Risky';
        lines.push(`| ${result.category.name} | ${safety} | ${formatSize(result.totalSize)} | ${result.items.length} |`);
      }
    }

    // Detailed breakdown
    lines.push('');
    lines.push('## Detailed Breakdown');
    lines.push('');

    for (const result of data.summary.results) {
      if (result.items.length > 0) {
        lines.push(`### ${result.category.name}`);
        lines.push('');
        lines.push(`- **Total Size:** ${formatSize(result.totalSize)}`);
        lines.push(`- **Items:** ${result.items.length}`);
        if (result.category.safetyNote) {
          lines.push(`- **Note:** ${result.category.safetyNote}`);
        }
        lines.push('');

        // Show top 10 items by size
        const topItems = [...result.items].sort((a, b) => b.size - a.size).slice(0, 10);
        if (topItems.length > 0) {
          lines.push('**Top items by size:**');
          lines.push('');
          for (const item of topItems) {
            lines.push(`- \`${item.name}\` - ${formatSize(item.size)}`);
          }
          lines.push('');
        }
      }
    }
  } else {
    // Clean report
    const dryRunLabel = data.dryRun ? ' (Dry Run)' : '';
    lines.push(`# Windows Cleaner CLI - Clean Report${dryRunLabel}`);
    lines.push('');
    lines.push(`**Generated:** ${date}`);
    lines.push(`**Duration:** ${Math.round(data.duration / 1000)}s`);
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    lines.push(`- **Space Freed:** ${formatSize(data.summary.totalFreedSpace)}`);
    lines.push(`- **Items Cleaned:** ${data.summary.totalCleanedItems.toLocaleString()}`);
    lines.push(`- **Errors:** ${data.summary.totalErrors}`);
    lines.push('');

    if (data.summary.results.length > 0) {
      lines.push('## Categories Cleaned');
      lines.push('');
      lines.push('| Category | Items | Space Freed | Errors |');
      lines.push('|----------|-------|-------------|--------|');

      for (const result of data.summary.results) {
        const errors = result.errors.length > 0 ? `${result.errors.length}` : '0';
        lines.push(`| ${result.category.name} | ${result.cleanedItems} | ${formatSize(result.freedSpace)} | ${errors} |`);
      }
    }

    // Show errors if any
    if (data.summary.totalErrors > 0) {
      lines.push('');
      lines.push('## Errors');
      lines.push('');
      for (const result of data.summary.results) {
        for (const error of result.errors) {
          lines.push(`- **${result.category.name}:** ${error}`);
        }
      }
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [Windows Cleaner CLI](https://github.com/sifly/windows-cleaner-cli)*');

  return lines.join('\n');
}

function generateHtmlReport(data: ReportData): string {
  const date = new Date(data.timestamp).toLocaleString();
  const isScan = data.type === 'scan';
  const title = isScan ? 'Scan Report' : `Clean Report${data.dryRun ? ' (Dry Run)' : ''}`;

  let categoriesHtml = '';
  let detailsHtml = '';

  if (isScan) {
    const summary = data.summary;
    categoriesHtml = summary.results
      .filter((r) => r.items.length > 0)
      .map((result) => {
        const safetyClass = result.category.safetyLevel;
        const safetyLabel = result.category.safetyLevel === 'safe' ? 'Safe' :
                           result.category.safetyLevel === 'moderate' ? 'Moderate' : 'Risky';
        return `
          <tr>
            <td>${result.category.name}</td>
            <td><span class="safety ${safetyClass}">${safetyLabel}</span></td>
            <td class="size">${formatSize(result.totalSize)}</td>
            <td class="number">${result.items.length}</td>
          </tr>`;
      })
      .join('\n');

    detailsHtml = summary.results
      .filter((r) => r.items.length > 0)
      .map((result) => {
        const topItems = [...result.items].sort((a, b) => b.size - a.size).slice(0, 10);
        const itemsList = topItems
          .map((item) => `<li><code>${escapeHtml(item.name)}</code> - ${formatSize(item.size)}</li>`)
          .join('\n');
        return `
          <div class="category-detail">
            <h3>${result.category.name}</h3>
            <p><strong>Size:</strong> ${formatSize(result.totalSize)} | <strong>Items:</strong> ${result.items.length}</p>
            ${result.category.safetyNote ? `<p class="note">${result.category.safetyNote}</p>` : ''}
            <ul>${itemsList}</ul>
          </div>`;
      })
      .join('\n');
  } else {
    const summary = data.summary;
    categoriesHtml = summary.results
      .map((result) => `
        <tr>
          <td>${result.category.name}</td>
          <td class="number">${result.cleanedItems}</td>
          <td class="size">${formatSize(result.freedSpace)}</td>
          <td class="number ${result.errors.length > 0 ? 'error' : ''}">${result.errors.length}</td>
        </tr>`)
      .join('\n');

    if (summary.totalErrors > 0) {
      const errorsList = summary.results
        .flatMap((r) => r.errors.map((e) => `<li><strong>${r.category.name}:</strong> ${escapeHtml(e)}</li>`))
        .join('\n');
      detailsHtml = `
        <div class="errors">
          <h3>Errors</h3>
          <ul>${errorsList}</ul>
        </div>`;
    }
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Windows Cleaner CLI - ${title}</title>
  <style>
    :root {
      --bg: #1a1a2e;
      --surface: #16213e;
      --primary: #0f3460;
      --accent: #e94560;
      --text: #eaeaea;
      --text-dim: #888;
      --safe: #4ade80;
      --moderate: #fbbf24;
      --risky: #f87171;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem;
    }
    .container { max-width: 900px; margin: 0 auto; }
    h1 { color: var(--accent); margin-bottom: 0.5rem; }
    h2 { color: var(--text); margin: 2rem 0 1rem; border-bottom: 2px solid var(--primary); padding-bottom: 0.5rem; }
    h3 { color: var(--accent); margin: 1.5rem 0 0.5rem; }
    .meta { color: var(--text-dim); margin-bottom: 2rem; }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0; }
    .summary-card {
      background: var(--surface);
      padding: 1.5rem;
      border-radius: 8px;
      border-left: 4px solid var(--accent);
    }
    .summary-card .label { color: var(--text-dim); font-size: 0.875rem; }
    .summary-card .value { font-size: 1.5rem; font-weight: bold; color: var(--safe); }
    table { width: 100%; border-collapse: collapse; background: var(--surface); border-radius: 8px; overflow: hidden; }
    th, td { padding: 0.75rem 1rem; text-align: left; }
    th { background: var(--primary); font-weight: 600; }
    tr:not(:last-child) td { border-bottom: 1px solid var(--primary); }
    .size, .number { text-align: right; }
    .safety { padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
    .safety.safe { background: rgba(74, 222, 128, 0.2); color: var(--safe); }
    .safety.moderate { background: rgba(251, 191, 36, 0.2); color: var(--moderate); }
    .safety.risky { background: rgba(248, 113, 113, 0.2); color: var(--risky); }
    .category-detail { background: var(--surface); padding: 1rem; border-radius: 8px; margin: 1rem 0; }
    .category-detail ul { margin: 0.5rem 0 0 1.5rem; }
    .category-detail li { margin: 0.25rem 0; }
    .note { color: var(--moderate); font-style: italic; }
    code { background: var(--primary); padding: 0.125rem 0.25rem; border-radius: 4px; font-size: 0.875rem; }
    .error { color: var(--risky); }
    .errors { background: rgba(248, 113, 113, 0.1); padding: 1rem; border-radius: 8px; border-left: 4px solid var(--risky); }
    .errors ul { margin-left: 1.5rem; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--primary); color: var(--text-dim); font-size: 0.875rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Windows Cleaner CLI</h1>
    <p class="meta">${title} - ${date}</p>

    <h2>Summary</h2>
    <div class="summary-grid">
      ${isScan ? `
        <div class="summary-card">
          <div class="label">Total Size</div>
          <div class="value">${formatSize(data.summary.totalSize)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Total Items</div>
          <div class="value">${data.summary.totalItems.toLocaleString()}</div>
        </div>
        <div class="summary-card">
          <div class="label">Categories</div>
          <div class="value">${data.summary.results.filter((r) => r.items.length > 0).length}</div>
        </div>
      ` : `
        <div class="summary-card">
          <div class="label">Space Freed</div>
          <div class="value">${formatSize(data.summary.totalFreedSpace)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Items Cleaned</div>
          <div class="value">${data.summary.totalCleanedItems.toLocaleString()}</div>
        </div>
        <div class="summary-card">
          <div class="label">Duration</div>
          <div class="value">${Math.round(data.duration / 1000)}s</div>
        </div>
      `}
    </div>

    <h2>Categories</h2>
    <table>
      <thead>
        <tr>
          <th>Category</th>
          ${isScan ? '<th>Safety</th>' : ''}
          ${isScan ? '<th class="size">Size</th>' : '<th class="number">Items</th>'}
          ${isScan ? '<th class="number">Items</th>' : '<th class="size">Freed</th>'}
          ${!isScan ? '<th class="number">Errors</th>' : ''}
        </tr>
      </thead>
      <tbody>
        ${categoriesHtml}
      </tbody>
    </table>

    ${detailsHtml ? `<h2>Details</h2>${detailsHtml}` : ''}

    <footer>
      Generated by <a href="https://github.com/sifly/windows-cleaner-cli" style="color: var(--accent);">Windows Cleaner CLI</a>
    </footer>
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
